Homework 1
AndreySinelnikov/AndreySinelnikov pull request #1
Opened 2021-08-05 19:35 UTC by AndreySinelnikov

2021-08-10 16:28 UTC, DmitryKhodakovsky requested changes
Please resolve comments

2021-08-10 16:28 UTC, DmitryKhodakovsky commented on pom.xml
> +                <version>2.22.2</version>
Why do you use `2.22.2` version for `surefire` plugin instead of `3.0.0-M5`?

2021-08-10 16:28 UTC, DmitryKhodakovsky commented on pom.xml
> +    <build>
Where is declaration and settings of the `maven-checkstyle-plugin`?

2021-08-10 16:28 UTC, DmitryKhodakovsky commented on pom.xml
> +        </dependency>
Why do you specify `maven-checkstyle-plugin` as dependency instead of plugin?

2021-08-10 16:28 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw1/AdditionTests.java
> +    public static Object[][] simpleLongValues_Data() {
Please follow Java Code Convention for the methods/variables/classes names

2021-08-10 16:28 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw1/DivisionTests.java
> +        calculator.div(a, b);
What do you test here?

2021-08-10 19:23 UTC, AndreySinelnikov commented on pom.xml
> +                <version>2.22.2</version>
3.0.0-M5 failed to download originally, so I set the version that worked; changed it to 3.0.0-M5, no problems now.

2021-08-10 19:40 UTC, AndreySinelnikov commented on pom.xml
> +    <build>
Added the declaration as it was specified in the example pom.xml.

2021-08-10 19:41 UTC, AndreySinelnikov commented on pom.xml
> +        </dependency>
Got dependency and plugin mixed up, removed the dependency.

2021-08-10 19:55 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw1/DivisionTests.java
> +        calculator.div(a, b);
Unlike Calculator's double division method, long division method has a zero argument check that throws NumberFormatException, so I reverse engineered this test from the fact.

2021-08-10 20:14 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw1/AdditionTests.java
> +    public static Object[][] simpleLongValues_Data() {
rewritten the names without underscores

2021-08-11 17:28 UTC, DmitryKhodakovsky approved these changes
Approved

2021-08-11 17:28 UTC, merged