Homework 2
AndreySinelnikov/AndreySinelnikov pull request #2
Opened 2021-08-10 21:21 UTC by AndreySinelnikov

2021-08-11 17:48 UTC, DmitryKhodakovsky requested changes
1. Please read requirements carefully for the HW
2. Please make `rebase` to the `master` branch
3. please check the tests, I am not able to run them

```
[INFO] 60 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.126 s
[INFO] Finished at: 2021-08-11T20:29:44+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project Andrey_Sinelnikov: Compilation failure: Compilation failure: 
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[11,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[12,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[13,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[14,34] package org.openqa.selenium.chrome does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[15,38] package org.openqa.selenium.support.ui does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/Utils.java:[6,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/Utils.java:[7,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:[14,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:[15,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:[16,27] package org.openqa.selenium does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:[17,34] package org.openqa.selenium.chrome does not exist
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/Utils.java:[11,54] cannot find symbol
[ERROR]   symbol:   class WebElement
[ERROR]   location: class com.epam.tc.hw2.Utils
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/Utils.java:[11,24] cannot find symbol
[ERROR]   symbol:   class WebElement
[ERROR]   location: class com.epam.tc.hw2.Utils
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/Utils.java:[15,61] cannot find symbol
[ERROR]   symbol:   class WebElement
[ERROR]   location: class com.epam.tc.hw2.Utils
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[24,9] cannot find symbol
[ERROR]   symbol:   class WebDriver
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[24,35] cannot find symbol
[ERROR]   symbol:   class ChromeDriver
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[34,31] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[35,31] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[36,31] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[37,31] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[39,9] cannot find symbol
[ERROR]   symbol:   class WebElement
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[39,54] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[43,9] cannot find symbol
[ERROR]   symbol:   class WebElement
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[43,56] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[44,33] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[45,33] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[47,32] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[49,26] cannot find symbol
[ERROR]   symbol:   variable WebElement
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex2/Exercise2.java:[51,32] cannot find symbol
[ERROR]   symbol:   variable By
[ERROR]   location: class com.epam.tc.hw2.ex2.Exercise2
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/tra [...]

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw1/AdditionTests.java
> +public class AdditionTests extends OperationTests {
From which branch did you create this one?
Why in this pull request exist files from `homework_1`?

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on pom.xml
> +    <dependencies>
I do not see any selenium dependencies here

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\Drivers\\Selenium\\chromedriver.exe");
This test could be run only on windows.
Please use `webdrivermanager`

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        webdriver.manage().window().maximize();
driver should be created in `@BeforeMethod`

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        webdriver.quit();
Driver should be closed in `@AfterMethod`

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw2/ex2/Exercise2TestData.java
> +    );
I suppose that test data could be merged into one class to avoid code duplication

2021-08-11 17:48 UTC, DmitryKhodakovsky commented on pom.xml
> +    <profiles>
I do not see active profile for the hw 2

2021-08-11 19:02 UTC, AndreySinelnikov commented on pom.xml
> +    <profiles>
added a profile

2021-08-11 19:02 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw2/ex2/Exercise2TestData.java
> +    );
data merged into one class

2021-08-11 19:03 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        webdriver.quit();
implemented @AfterMethod

2021-08-11 19:03 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        webdriver.manage().window().maximize();
implemented @BeforeMethod

2021-08-11 19:04 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw2/ex1/Exercise1.java
> +        System.setProperty("webdriver.chrome.driver", "C:\\Drivers\\Selenium\\chromedriver.exe");
added webdrivermanager dependency, uses it to manage drivers now

2021-08-11 19:04 UTC, AndreySinelnikov commented on pom.xml
> +    <dependencies>
added selenium dependency

2021-08-11 19:05 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw1/AdditionTests.java
> +public class AdditionTests extends OperationTests {
rebased from main

2021-08-11 21:35 UTC, DmitryKhodakovsky requested changes
Please resolve comments and errors during maven compilation

```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (validate) @ Andrey_Sinelnikov ---
[INFO] Starting audit...
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:7:1: Wrong lexicographical order for 'com.epam.tc.hw2.CommonTestData.TEST_USER_DATA' import. Should be before 'com.epam.tc.hw2.ex1.Exercise1TestData.LEFT_SECTION_EXPECTED_TEXTS'. [CustomImportOrder]
[ERROR] /Users/dmitry_khodakovsky/EPAM-Projects/training_center/automation-summer-2021-jul/AndreySinelnikov/src/test/java/com/epam/tc/hw2/ex1/Exercise1.java:9:1: Wrong lexicographical order for 'com.epam.tc.hw2.CommonTestData.URL_DATA' import. Should be before 'com.epam.tc.hw2.ex1.Exercise1TestData.UPPER_NAV_BAR_EXPECTED_TEXTS'. [CustomImportOrder]
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.657 s
[INFO] Finished at: 2021-08-12T00:31:20+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (validate) on project Andrey_Sinelnikov: Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.42 with https://raw.githubusercontent.com/DmitryKhodakovsky/epam-training-center-code-checkers-configurations/main/checkstyle/checkstyle.xml ruleset. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

2021-08-11 21:35 UTC, DmitryKhodakovsky commented on src/test/java/com/epam/tc/hw2/ex2/Exercise2.java
> +
I suppose that this peace of code could be extacted to the base class to avoid code duplicatons

2021-08-12 09:19 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw2/ex2/Exercise2.java
> +
reordered imports statements, moved common methods/attributes to parent Exercise class

2021-08-16 08:14 UTC, DmitryKhodakovsky approved these changes
Hw2 accepted

2021-08-16 08:14 UTC, merged