Homework 7 jdi
AndreySinelnikov/AndreySinelnikov pull request #7
Opened 2021-09-16 20:29 UTC by AndreySinelnikov

2021-09-17 21:41 UTC, pnatashap requested changes

2021-09-17 21:41 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7_jdi/JdiTest.java
> +        loginAs(ROMAN);
login is not a part of the test, it's only a precondition in this case

2021-09-17 21:41 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7_jdi/site/MetalsAndColorsPage.java
> +    public static void logout() {
A bit strange, that login and logout are located in different pages

2021-09-18 12:35 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw7_jdi/JdiTest.java
> +        loginAs(ROMAN);
moved to BeforeMethod in TestsInit

2021-09-18 12:35 UTC, AndreySinelnikov commented on src/test/java/com/epam/tc/hw7_jdi/site/MetalsAndColorsPage.java
> +    public static void logout() {
logout method moved to JdiSite

2021-09-22 18:41 UTC, pnatashap approved these changes

2021-09-22 18:41 UTC, pnatashap commented on src/test/java/com/epam/tc/hw7_jdi/JdiTest.java
> +        logout();
We do not need to logout for every test. Parametrized test is needed to check functionality, for this case login is a precondition

2021-09-25 20:04 UTC, merged